# Generated by Django 3.0.7 on 2020-10-09 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(default='', max_length=100)),
                ('channel_name', models.CharField(default='', max_length=100)),
                ('channel_text', models.CharField(default='', max_length=100)),
                ('listen', models.BooleanField()),
            ],
            options={
                'ordering': ('channel_name', 'channel_id'),
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_id', models.CharField(default='T02FBR21U', max_length=9)),
                ('team_domain', models.CharField(default='inputlogic', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('link', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000, null=True)),
                ('image', models.TextField(max_length=1000, null=True)),
                ('msg', models.CharField(default='', max_length=100)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Channel')),
            ],
            options={
                'ordering': ('title', 'link'),
            },
        ),
        migrations.AddField(
            model_name='channel',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='links.Team'),
        ),
    ]
